In [50]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [51]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [52]:
arquivo = 'z0019_2.csv'

df = pd.read_csv(f'c:\\Users\\Guilherme\\Documents\\Anhanguera\\Projeto Python SQL GIT\\My-Project-2\\landing\\{arquivo}', sep=';')

data_ingestao = datetime.now()
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao
0,10003,CHAVE DE FENDA,BT10,100,50,z0019_2.csv,2026-04-26 09:34:20.905235
1,10004,ALICATE,BT20,100,200,z0019_2.csv,2026-04-26 09:34:20.905235
2,10005,SERROTE,BT30,100,0,z0019_2.csv,2026-04-26 09:34:20.905235

In [53]:
print(datetime.now())

2026-04-26 09:34:20.916396

In [54]:
con.execute('''
CREATE TABLE IF NOT EXISTS bronze_produtos (
    NATBR VARCHAR,
    MAKTX VARCHAR,
    WERKS VARCHAR,
    MAINS VARCHAR,
    LABST VARCHAR,
    nome_arquivo VARCHAR,
    data_ingestao TIMESTAMP
)
''')

In [55]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [62]:
resultado = con.execute('SELECT * FROM bronze_z0019').fetchdf()
resultado.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-04-26 09:13:46.217099
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-04-26 09:13:46.217099
2,10003,CHAVE DE FENDA,BT10,100,50,z0019_1.csv,2026-04-26 09:13:46.217099
3,10003,CHAVE INGLESA,BT10,100,50,z0019_2.csv,2026-04-26 09:32:35.491618
4,10004,ALICATE,BT20,100,200,z0019_2.csv,2026-04-26 09:32:35.491618

In [57]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [63]:
con.close()